codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        flags:
          - unittests
          - main-branch
    patch:
      default:
        target: 50%
        threshold: 5%

flags:
  unittests:
    paths:
      - app/
    carryforward: false
  main-branch:
    paths:
      - app/
    carryforward: false

comment:
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tests/"
  - "data/"
  - ".venv/"
  - "venv/"
  - "**/__pycache__"
