# Safety CLI v3 Policy Configuration for DNSSEC Validator
# This local policy enforces security standards when Safety Platform policy is not available
# Documentation: https://docs.safetycli.com/safety-docs/safety-3.0/policy-file

version: "3.0"

# Scanning behavior configuration
scanning-settings:
  system:
    targets:
      - "/"
  exclude:
    - ".git"
    - ".venv"
    - "venv"
    - "*.pyc"
    - "__pycache__"
  max-depth: 6

# Report configuration
report:
  dependency-vulnerabilities:
    enabled: true
    # DO NOT auto-ignore vulnerabilities
    auto-ignore-in-report:
      python:
        environment-results: false  # Scan virtual environments
        unpinned-requirements: false  # Scan unpinned dependencies (>=)
      cvss-severity: null
      vulnerabilities: {}

# Fail scan configuration - exit with non-zero code on vulnerabilities
fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - critical
        - high
      exploitability:
        - critical
        - high

# Security updates configuration
security-updates:
  dependency-vulnerabilities:
    auto-security-updates-limit:
      - patch

# Installation policy
installation:
  deny:
    vulnerabilities:
      warning-on-any-of:
        cvss-severity:
          - critical
          - high
          - medium
          - low
  default-action: allow
